// <auto-generated />
namespace ChainOfStores.EFData.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addlastdayofbookingtobooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addlastdayofbookingtobooking));
        
        string IMigrationMetadata.Id
        {
            get { return "202106060555073_add last day of booking to booking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
